### ISSUE TITLE
how to run it in real time

### ISSUE THREAD

**Issue by imdsafi09** [hehern/PIXOR#2]
Thanks for your nice works, my question is how to use our real time lidar data inside the code. can you please guide me

**Comment by hehern** [comment]
Firstly, to ensure reliability, you must convert your lidar data to the same coordinate system as the kitti data. Secondly, you should change the lidar topic name in "pixor_ros_20200331.py" line 317. Then python the pixor_ros_20200331.py to sub your lidar topic, and you can sub obs points and markers in rviz.
